kind: pipeline
type: docker
name: default

steps:
  - name: Upload to mario
    image: appleboy/drone-scp
    settings:
      host: mario.smashmc.eu
      username:
        from_secret: mario_username
      key:
        from_secret: mario_key
      port: 22334
      target: /tmp/cicd/language
      source: ./*
    when:
      branch:
        - main
      event:
        - push

  - name: Copy to template
    image: appleboy/drone-ssh
    settings:
      host: mario.smashmc.eu
      username:
        from_secret: mario_username
      key:
        from_secret: mario_key
      port: 22334
      script:
        - rm -rf /home/minecraft/file/translation-files
        - mv /tmp/cicd/language/* /home/minecraft/file/translation-files
        - touch /tmp/langrl
    when:
      branch:
        - main
      event:
        - push

  # Notify Telegram that new translations were added
    # - name: Notify on Telegram
    #   image: appleboy/drone-telegram
      #   when:
        #      status:
        #        - success
    #        - failure
      #    settings:
        #    token:
      #      from_secret: telegram_token
        #     to:
      #       from_secret: telegram_chat_id
      #     format: markdown
  #     message: "✅ New translations were added to `{{repo.name}}`\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`\n\n🌐 [{{commit.message}}]({{commit.link}})"